// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcuydhmedxzjuyqdjwts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdXlkaG1lZHh6anV5cWRqd3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MDAwOTEsImV4cCI6MjA1NDA3NjA5MX0.r1br4ABegnzT_5huztTWtthpeV8n5esVx93LnUqcY5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);